
name: testrix

include:
  - platform/docker-compose.yml
  - products/automation-portal/docker-compose.yml
  - products/api-testing/docker-compose.yml
  - products/genai/docker-compose.yml
  - products/performance-testing/docker-compose.yml
  - products/testcase-generator/docker-compose.yml
