package com.testrix.platform.audit;

public enum AuditAction {
    LOGIN,
    LOGOUT,
    FAILED_LOGIN,
    OTP_SENT,
    OTP_VERIFIED,
    PASSWORD_CHANGE,
    PASSWORD_RESET,
    EMAIL_CHANGE,
    PROFILE_UPDATE,
    USER_CREATE,
    USER_UPDATE,
    USER_DISABLE,
    USER_ENABLE,
    USER_PASSWORD_RESET,
    USER_DELETE,
    ROLE_CHANGE,
    WORKSPACE_REQUESTED,
    WORKSPACE_APPROVED,
    WORKSPACE_REJECTED,
    WORKSPACE_SUSPENDED,
    WORKSPACE_REACTIVATED,
    RATE_LIMIT_CLEARED
}
